branch-defaults:
  main:
    environment: grade-ielts-dev
  master:
    environment: grade-ielts-dev2
    group_suffix: null
environment-defaults:
  grade-ielts-dev:
    branch: null
    repository: null
  grade-ielts-dev-2:
    branch: null
    repository: null
  grade-ielts-dev2:
    branch: null
    repository: null
global:
  application_name: grade-ielts
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
